#!/bin/sh
### BEGIN INIT INFO
# Provides:          work_timerd
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop work_timerd.
# Description:       This script starts/stops work_timerd.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

if [ $( id -u ) != 0 ]; then
	echo "ERROR: Must be run as root"
	exit 1
fi

case "$1" in
  start)
	su android -c /usr/local/sbin/work_timerd & >/dev/null
	;;
  restart|reload|force-reload)
	killall servod
	su android -c /usr/local/sbin/work_timerd & >/dev/null
	;;
  stop)
	killall work_timerd
	;;
  status)
	
	;;
  *)

esac

exit 0

