#!/bin/bash

# ./push "xxx"

git add .;

git commit -am "<$1>";

git remote add origin https://github.com/guomingyi/work_timerd.git

git pull origin master;   

git push -u origin master;


exit 0









